### ISSUE TITLE
Update all Component CI to use Central Github workflow

### ISSUE THREAD

**Issue by freekvandeven** [Iconica-Development/.github#2]
All Iconica components should use the starter workflow that is mentioned on the main page or use the melos variant. That way we can easily update all the CI

**Comment by mighttymike** [comment]
These are the packages that still need the Component CI and/or the iconica Linter.
Please check the package you updated:
- [ ] flutter_form_wizard
- [ ] flutter_registration
- [ ] flutter_input_library
- [ ] flutter_hooks_iconica_utilities
- [ ] flutter_image_progression
- [ ] flutter_bottom_alert_dialog
- [ ] flutter_animated_toggle
- [ ] flutter_login_widget
- [ ] flutter_menu
- [ ] flutter_image_picker
- [ ] flutter_roadmap_component
- [ ] flutter_login_service
- [ ] flutter_data_interface
- [ ] flutter_single_character_input
- [ ] flutter_grid_to_list
- [ ] flutter_stepper
- [ ] flutter_multi_child_animated_switcher
- [ ] flutter_dialogs
- [ ] flutter_address_form
